-- Add primer columns to neighborhoods for in-depth research primers.
-- Primers are 500-1000 word summaries grounded in publication abstracts
-- and extracted key findings, generated by LLM.
--
-- Usage:
--   psql rmbl_knowledge_hub < scripts/sql/add-neighborhood-primers.sql

ALTER TABLE neighborhoods ADD COLUMN IF NOT EXISTS primer TEXT;
ALTER TABLE neighborhoods ADD COLUMN IF NOT EXISTS primer_type TEXT;        -- 'research', 'policy', 'mixed'
ALTER TABLE neighborhoods ADD COLUMN IF NOT EXISTS primer_generated_at TIMESTAMPTZ;
ALTER TABLE neighborhoods ADD COLUMN IF NOT EXISTS primer_citations JSONB DEFAULT '[]';
