-- Backfill provenance for existing Tier 1 LLM-generated artifacts.
--
-- Per the project owner: all Tier 1 artifacts existing as of this migration
-- were generated by Claude Opus 4.7 around 2026-05-15. Forward-looking writes
-- (from updated generation scripts) populate exact values; this fills the
-- gap for what's already in the database.
--
-- Idempotent: only updates rows where the provenance field is NULL but the
-- content field is populated. Re-running is safe and a no-op.

-- Neighborhood primers
UPDATE neighborhoods
   SET primer_model = 'claude-opus-4-7'
 WHERE primer IS NOT NULL AND primer_model IS NULL;

UPDATE neighborhoods
   SET primer_generated_at = '2026-05-15 00:00:00+00'::timestamptz
 WHERE primer IS NOT NULL AND primer_generated_at IS NULL;

-- Era primers (eras already has both columns; backfill only if NULL)
UPDATE eras
   SET primer_model = 'claude-opus-4-7'
 WHERE primer IS NOT NULL AND primer_model IS NULL;

UPDATE eras
   SET primer_generated_at = '2026-05-15 00:00:00+00'::timestamptz
 WHERE primer IS NOT NULL AND primer_generated_at IS NULL;

-- Frontier syntheses
UPDATE frontiers
   SET synthesis_model = 'claude-opus-4-7'
 WHERE frontier_description IS NOT NULL AND synthesis_model IS NULL;

-- Planning theme descriptions
UPDATE frontier_planning_themes
   SET description_model = 'claude-opus-4-7'
 WHERE summary IS NOT NULL AND description_model IS NULL;

-- Planning cluster descriptions
UPDATE frontier_planning_clusters
   SET description_model = 'claude-opus-4-7'
 WHERE summary IS NOT NULL AND description_model IS NULL;

-- Long-reach opportunity syntheses (description is NOT NULL on this table)
UPDATE frontier_long_reach_opportunities
   SET synthesis_model = 'claude-opus-4-7'
 WHERE synthesis_model IS NULL;
